# Generated by Django 5.1.7 on 2025-06-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='analise_concorrencia',
            field=models.TextField(blank=True, null=True, verbose_name='Análise da Concorrência'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='canais_comunicacao',
            field=models.TextField(blank=True, null=True, verbose_name='Canais de Comunicação e Perfis'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cargo_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo do Responsável'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='comportamento_compra',
            field=models.TextField(blank=True, null=True, verbose_name='Comportamento de Compra'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contato_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato do Responsável'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='descricao_publico',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Público-Alvo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='equipe_marketing',
            field=models.TextField(blank=True, null=True, verbose_name='Equipe de Marketing'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='expectativas_agencia',
            field=models.TextField(blank=True, null=True, verbose_name='Expectativas da Agência'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='kpis_empresa',
            field=models.TextField(blank=True, null=True, verbose_name='KPIs da Empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='lista_produtos_servicos',
            field=models.TextField(blank=True, null=True, verbose_name='Produtos ou Serviços'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='mensagem_principal',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem Principal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='metas_especificas',
            field=models.TextField(blank=True, null=True, verbose_name='Metas Específicas'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='necessidades_desejos',
            field=models.TextField(blank=True, null=True, verbose_name='Necessidades e Desejos do Público'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='objetivos_marketing',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivos de Marketing'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='objetivos_posicionamento',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivos de Posicionamento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pontos_fortes_fracos_concorrencia',
            field=models.TextField(blank=True, null=True, verbose_name='Pontos Fortes e Fracos da Concorrência'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='posicionamento_atual',
            field=models.TextField(blank=True, null=True, verbose_name='Posicionamento Atual'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='recursos_tecnologicos',
            field=models.TextField(blank=True, null=True, verbose_name='Recursos Tecnológicos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='responsavel_contrato',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsável pelo Contrato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='resultados_esperados',
            field=models.TextField(blank=True, null=True, verbose_name='Resultados Esperados'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tom_voz',
            field=models.TextField(blank=True, null=True, verbose_name='Tom de Voz da Marca'),
        ),
    ]
