# Generated by Django 5.1.7 on 2025-06-14 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_analise_concorrencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanha',
            name='produto_servico',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='aprovacoes_necessarias',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='cac_maximo',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='campanhas_anteriores_empresa',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='campanhas_concorrentes_benchmark',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='canais_utilizados',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='comportamentos_publico',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='cpa_maximo',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='cpc_maximo',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='ctr_esperado',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='diferenciacao_campanha',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='dor_unica_resolve',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='especificacoes_anuncios',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='especificidades_canais',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='estrategias_otimizacao',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='estrutura_funil_definida',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='formularios_configurados',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='frequencia_monitoramento',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='genero_publico',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='idade_publico',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='interesses_publico',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='landing_page_url',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='ltv_esperado',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='mensagem_fundo_funil',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='mensagem_meio_funil',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='mensagem_topo_funil',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='meta_aumento_vendas',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='meta_leads_mes',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='meta_visitas_site',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='metas_conversao',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='metodo_medicao_conversao',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='necessidades_desejos_publico',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='objetivos_marketing',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='posicionamento_vs_concorrencia',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='promocao_preco',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='requisitos_tecnicos',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='restricoes_legais',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='roas_minimo',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='roi_esperado',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='sentimentos_decisao_compra',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='tempo_ciclo_venda',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='ticket_medio_atual',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='ticket_medio_desejado',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='tom_voz_campanha',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='transformacao_desejada',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='utms_personalizadas',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='valor_unico',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='whatsapp_business_integrado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='briefing_completo',
            field=models.BooleanField(default=False, verbose_name='Briefing Estratégico Completo?'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_briefing',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão do Briefing'),
        ),
        migrations.CreateModel(
            name='ClienteChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_imagens_videos', models.BooleanField(default=False, verbose_name='Possui banco de imagens/vídeos?')),
                ('responsavel_conteudo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsável por conteúdo')),
                ('acesso_criativos', models.BooleanField(default=False, verbose_name='Tem acesso a criativos utilizados?')),
                ('pasta_materiais', models.URLField(blank=True, null=True, verbose_name='Link da pasta de materiais')),
                ('liberacao_meta', models.BooleanField(default=False, verbose_name='Liberação Meta com cliente')),
                ('business_manager_ativo', models.BooleanField(default=False, verbose_name='Business Manager ativo?')),
                ('dominio_verificado', models.BooleanField(default=False, verbose_name='Domínio verificado?')),
                ('pixel_instalado', models.BooleanField(default=False, verbose_name='Pixel instalado?')),
                ('conversoes_api_ativas', models.BooleanField(default=False, verbose_name='Conversões API ativas?')),
                ('acesso_conta_anuncios', models.BooleanField(default=False, verbose_name='Acesso à conta de anúncios?')),
                ('conta_google_ads', models.BooleanField(default=False, verbose_name='Conta no Google Ads?')),
                ('search_console', models.BooleanField(default=False, verbose_name='Google Search Console configurado?')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='core.cliente')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checklist Operacional',
                'verbose_name_plural': 'Checklists Operacionais',
            },
        ),
        migrations.DeleteModel(
            name='ProdutoServicoEvento',
        ),
    ]
