# Generated by Django 5.1.7 on 2025-07-07 08:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_campanha_produto_servico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='lista_produtos_servicos',
        ),
        migrations.CreateModel(
            name='ProdutoServicoEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('produto', 'Produto'), ('servico', 'Serviço'), ('curso', 'Curso'), ('evento', 'Evento')], max_length=20, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto/Serviço/Curso/Evento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('caracteristicas_beneficios', models.TextField(blank=True, null=True, verbose_name='Características e Benefícios')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço (R$)')),
                ('posicionamento_mercado', models.TextField(blank=True, null=True, verbose_name='Posicionamento no Mercado')),
                ('mensagens_materiais_marketing', models.TextField(blank=True, help_text='Quais mensagens e materiais serão usados para promover?', null=True, verbose_name='Mensagens e Materiais de Marketing')),
                ('data_lancamento', models.DateField(blank=True, null=True, verbose_name='Data de Lançamento')),
                ('cronograma_producao', models.TextField(blank=True, null=True, verbose_name='Cronograma para Produção e Distribuição')),
                ('pacotes_opcoes', models.TextField(blank=True, help_text='Quais pacotes e opções serão oferecidos?', null=True, verbose_name='Pacotes e Opções de Serviço')),
                ('objetivos_venda', models.TextField(blank=True, help_text='Ex: gerar inscrições, aumentar receita', null=True, verbose_name='Objetivos da Venda')),
                ('metas_especificas', models.TextField(blank=True, help_text='Ex: número de inscrições, receita esperada', null=True, verbose_name='Metas Específicas')),
                ('formato', models.CharField(blank=True, help_text='Online, presencial, híbrido', max_length=100, null=True, verbose_name='Formato')),
                ('duracao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Duração')),
                ('agenda', models.TextField(blank=True, null=True, verbose_name='Agenda/Programação')),
                ('palestrantes_instrutores', models.TextField(blank=True, null=True, verbose_name='Palestrantes e Instrutores')),
                ('materiais_recursos', models.TextField(blank=True, help_text='Materiais fornecidos aos participantes', null=True, verbose_name='Materiais e Recursos')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_servicos', to='core.cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Produto/Serviço/Evento',
                'verbose_name_plural': 'Produtos/Serviços/Eventos',
                'ordering': ['-created_at'],
            },
        ),
    ]
