# Generated by Django 5.1.7 on 2025-07-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_cliente_lista_produtos_servicos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='historia_empresa',
            field=models.TextField(blank=True, help_text='História da empresa: fundação, evolução, marcos importantes', null=True, verbose_name='História da Empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='missao',
            field=models.TextField(blank=True, help_text='Qual é o propósito da empresa? Por que ela existe?', null=True, verbose_name='Missão da Empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valores',
            field=models.TextField(blank=True, help_text='Quais são os princípios e valores que norteiam a empresa?', null=True, verbose_name='Valores da Empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='visao',
            field=models.TextField(blank=True, help_text='Onde a empresa quer chegar? Como se vê no futuro?', null=True, verbose_name='Visão da Empresa'),
        ),
    ]
